### ISSUE TITLE
proposal: use go comments as doc if none specified

### ISSUE THREAD

**Issue by costela** [danielgtaylor/huma#210]
Since APIs may be composed from disparate parts of the code-base, one may end up composing inputs/outputs with structs from packages/modules that are not specific to huma.
One can of course add wrapper types for all input/output parts, but IMHO it would be helpful to try to extract more information from existing types that are huma-agnostic.

For this, I propose doing what godoc does and using code-adjacent comments as a source for API description. So:
```go
type Foo struct {
  Bar string // some helpful comment
}
```

Would become:
```yaml
Foo:
  type: object
  additionalProperties: false
  properties:
    bar:
      type: string
      description: some helpful comment
```

Previous-line comments should work analogously.

This would help with progressive adoption.

WDYT? Does this have some obvious drawback I'm overlooking?
