### ISSUE TITLE
Best way to cancel a request from a middleware?

### ISSUE THREAD

**Issue by martin31821** [danielgtaylor/huma#241]
Hi,

thanks for the awesome piece of software, it's been a really nice ride so far, but I've stumbled upon a problem I haven't been able to solve yet:

I'm trying to implement a simple jwt validation middleware and I wanted to cancel (i.e. not call the operation handler) from my middleware, but there seems to be no way to indicate an error in the middleware chain.

How would I best do this? 
Can I just not call "next" and write a body?
How would I then generate the nice error objects?

**Comment by danielgtaylor** [comment]
@martin31821 that's right, you just skip calling `next(ctx)` if you want the middleware to terminate the request processing chain.

You can use the [`huma.WriteErr`](https://pkg.go.dev/github.com/danielgtaylor/huma/v2#WriteErr) utility function for returning an error, which will use the API's registered error model and do content negotiation with the registered formats. Here's a quick example to trigger via query param:

```go
api.UseMiddleware(func(ctx huma.Context, next func(ctx huma.Context)) {
	if ctx.Query("error") == "true" {
		huma.WriteErr(api, ctx, http.StatusInternalServerError, "Some friendly message", fmt.Errorf("error detail"))
		return
	}

	next(ctx)
})
```

You can also use [`huma.ErrorDetail`](https://pkg.go.dev/github.com/danielgtaylor/huma/v2#ErrorDetail) instead of `fmt.Errorf(...)` to provide more information to the client when appropriate.

Using the [greeting example API](https://huma.rocks/tutorial/your-first-api/#operation), you would trigger this by going to http://localhost:8888/greeting/world?error=true and see a response like this:

```yaml
$ restish :8888/greeting/world?error=true
HTTP/1.1 500 Internal Server Error
Content-Length: 154
Content-Type: application/problem+cbor
Date: Thu, 15 Feb 2024 05:17:01 GMT

{
  $schema: "http://localhost:8888/schemas/ErrorModel.json"
  detail: "Some friendly message"
  errors: [
    {
      message: "error detail"
    }
  ]
  status: 500
  title: "Internal Server Error"
}
```
