### ISSUE TITLE
Validation for nested to array primitive types.

### ISSUE THREAD

**Issue by superstas** [danielgtaylor/huma#493]
Hi there!

I want to ask about validating primitive types nested in an array.

For example, I've got the following input:
```go
type Input struct {
	Body struct {
		ID  int   `json:"id" required:"true" minimum:"1" maximum:"10"`
		IDs []int `json:"ids" required:"true" minItems:"1" maxItems:"4"`
	}
}
```
Full code of the example: https://go.dev/play/p/hp1CsyyU6dt

Huma generates the following OAS spec for this type
```yaml
    InputBody:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - https://example.com/schemas/InputBody.json
          format: uri
          readOnly: true
          type: string
        id:
          format: int64
          maximum: 10
          minimum: 1
          type: integer
        ids:
          items:
            format: int64
            type: integer
          maxItems: 4
          minItems: 1
          type: array
      required:
        - id
        - ids
      type: object
```
![Screenshot from 2024-07-01 15-52-43](https://github.com/danielgtaylor/huma/assets/499721/05ce1995-2e20-4d58-a25b-1532a02e9510)

Is there a way to specify validation rules by using struct tags to get the same validation rules for `ids` as for `id`?
```
...
         id:
          format: int64
          maximum: 10
          minimum: 1
          type: integer
        ids:
          items:
            format: int64
            type: integer
            maximum: 10  <-- Added 
            minimum: 1  <-- Added
          maxItems: 4
          minItems: 1
          type: array
...
```
![Screenshot from 2024-07-01 15-51-34](https://github.com/danielgtaylor/huma/assets/499721/ec88f78d-17ca-4707-bedf-96c6d76fe93b)

Thank you.
