### ISSUE TITLE
OpenAPI spec does not support "null" type

### ISSUE THREAD

**Issue by krisatverbidio** [danielgtaylor/huma#539]
The new "null" types added in commit 72a101dce9a18e0febfa040ca1d324699d0dfa60 are not valid per the spec (https://swagger.io/docs/specification/data-models/data-types/).  This causes at least one typescript generator to generate `any[]` types instead of using the type in `$ref`.

For example, this:

```yaml
components:
  schemas:
    PropertyName:
      properties:
        propName:
           type:
             - array
             - "null"
```

should be replaced with this:

```yaml
components:
  schemas:
    PropertyName:
      properties:
        propName:
           type: array
           nullable: true
```

I can work on a fix in the coming days. I just wanted to create this issue for tracking purposes.
